const FILES=['products','stores','sightings','schedules'];
const db={};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>new Date(d).toLocaleString([], {dateStyle:'medium',timeStyle:'short'});
const nowLocal=()=>new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);
const fresh=r=>Date.now()-new Date(r.seenAt).getTime()<7200000;
const product=id=>db.products.find(p=>p.id===id);
const store=id=>db.stores.find(s=>s.id===id);
const save=k=>localStorage.setItem('crt_'+k,JSON.stringify(db[k]));
const logo=s=>`assets/icons/${s.retailer.toLowerCase()}.svg`;

async function boot(){
  for(const f of FILES){const local=localStorage.getItem('crt_'+f);db[f]=local?JSON.parse(local):await fetch(`data/${f}.json`).then(r=>r.json())}
  normalize();bind();renderAll();
}
function normalize(){
 db.products.forEach(p=>{p.favorite=!!p.favorite;p.active=p.active!==false;p.game=p.game||((p.category==='TCG')?p.subcategory:'');p.brand=p.brand||((p.category==='Squishies')?p.subcategory:'');p.productName=p.productName||p.name;p.setName=p.setName||'';p.beyModel=p.beyModel||'';p.beyType=p.beyType||p.subcategory||'';});
 db.sightings.forEach(r=>{r.updates=r.updates||[];r.quantityKnown=r.quantityKnown??r.quantity!=='';});
 db.schedules.forEach(s=>s.updates=s.updates||[]);
}
function bind(){
 $('nav').addEventListener('click',e=>{const b=e.target.closest('button[data-view]');if(!b)return;showView(b.dataset.view);closeMobileMenu()});
 $('mobileMenuBtn').onclick=()=>{const open=$('sidebar').classList.toggle('open');$('navBackdrop').classList.toggle('show',open);$('mobileMenuBtn').setAttribute('aria-expanded',open)};
 $('navBackdrop').onclick=closeMobileMenu;
 $('addProductBtn').onclick=()=>{$('productForm').reset();updateProductFields();$('productDialog').showModal()};
 $('addSightingBtn').onclick=()=>{fillSelects();$('sightingForm').seenAt.value=nowLocal();$('sightingDialog').showModal()};
 document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
 $('productCategory').onchange=updateProductFields;$('squishyBrand').onchange=updateProductFields;
 $('productForm').onsubmit=addProduct;$('sightingForm').onsubmit=addSighting;$('statusForm').onsubmit=saveStatusUpdate;$('scheduleForm').onsubmit=saveSchedule;
 document.addEventListener('click',e=>{if(!e.target.closest('.menu-wrap'))document.querySelectorAll('.context-menu').forEach(m=>m.hidden=true)});
}
function closeMobileMenu(){$('sidebar').classList.remove('open');$('navBackdrop').classList.remove('show');$('mobileMenuBtn').setAttribute('aria-expanded','false')}
function showView(v){document.querySelectorAll('.view').forEach(x=>x.classList.remove('active'));$(v).classList.add('active');document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('pageTitle').textContent={mapview:'Map',settings:'Data'}[v]||v[0].toUpperCase()+v.slice(1);if(v==='mapview')setTimeout(drawMap,50)}
function renderAll(){fillSelects();renderDashboard();renderProducts();renderStores();renderCalendar();renderWatchlist();renderHistory();renderSettings();if($('mapview').classList.contains('active'))drawMap()}
function updateProductFields(){const c=$('productCategory').value;const isT=c==='TCG',isS=c==='Squishies',isB=c==='Beyblade';$('tcgGameWrap').hidden=!isT;$('setWrap').hidden=!isT;$('brandWrap').hidden=!isS;$('productNameWrap').hidden=isB;$('beyModelWrap').hidden=!isB;$('beyTypeWrap').hidden=!isB;$('beyLinks').hidden=!isB;$('productForm').productName.required=!isB;$('productForm').beyModel.required=isB}
function productTitle(p){if(p.category==='Beyblade')return `Beyblade: ${p.beyModel||p.productName||p.name}`;if(p.category==='TCG')return [p.game,p.setName,p.productName].filter(Boolean).join(' · ');if(p.category==='Squishies')return [p.brand,p.productName].filter(Boolean).join(' · ');return p.name}
function productMeta(p){if(p.category==='TCG')return [p.game,p.setName].filter(Boolean).join(' · ');if(p.category==='Squishies')return p.brand==='Taba'&&/smusher/i.test(p.productName)?'Taba · Smushers':p.brand;if(p.category==='Beyblade')return p.beyType;return p.subcategory||''}
function reportList(rows){if(!rows.length)return '<div class="empty">No reports yet.</div>';return `<div class="list">${rows.sort((a,b)=>new Date(b.seenAt)-new Date(a.seenAt)).map(r=>{const p=product(r.productId),s=store(r.storeId);return `<div class="item clickable cat-${p?.category||''}" onclick="window.openReport('${r.id}')"><div class="thumb">${p?.image?`<img src="${esc(p.image)}" alt="">`:esc((p?.category||'?')[0])}</div><div><h3>${esc(productTitle(p||{}))}</h3><div><strong>${esc(s?.name||'Unknown store')}</strong> · <span class="status-${r.status}">${esc(r.status.replaceAll('-',' '))}</span>${r.quantityKnown?` · Qty ${esc(r.quantity)}`:''}</div><small class="${fresh(r)?'fresh':'stale'}">${fresh(r)?'Fresh':'Stale'} · ${fmt(r.seenAt)}</small><div class="muted">${esc(r.inStoreLocation||r.notes||'')}</div></div><div class="report-actions" onclick="event.stopPropagation()"><button class="btn primary" onclick="window.openStatusUpdate('${r.id}')">Update</button><button class="btn" onclick="window.copyReport('${r.id}')">Discord</button><div class="menu-wrap"><button class="btn kebab" onclick="window.toggleMenu(event,'report-${r.id}')">⋮</button><div class="context-menu" id="menu-report-${r.id}" hidden><button class="btn danger" onclick="window.requestDelete('sighting','${r.id}')">Delete entry</button></div></div></div></div>`}).join('')}</div>`}
function renderDashboard(){const freshRows=db.sightings.filter(fresh),staleRows=db.sightings.filter(r=>!fresh(r));$('dashboard').innerHTML=`<div class="grid"><div class="card metric"><span>Fresh reports</span><strong>${freshRows.length}</strong></div><div class="card metric"><span>Watched products</span><strong>${db.products.filter(p=>p.favorite).length}</strong></div><div class="card metric"><span>Stores with reports</span><strong>${new Set(db.sightings.map(r=>r.storeId)).size}</strong></div><div class="card metric"><span>Stale reports</span><strong>${staleRows.length}</strong></div></div><h2>Recent sightings</h2>${reportList(db.sightings.slice())}`}
function productCard(p,layout){const reports=db.sightings.filter(r=>r.productId===p.id);const last=reports.sort((a,b)=>new Date(b.seenAt)-new Date(a.seenAt))[0];const body=`<div class="thumb ${layout==='grid'?'large':''}">${p.image?`<img src="${esc(p.image)}" alt="">`:esc(p.category[0])}</div><div><h3>${esc(productTitle(p))}</h3><span class="badge">${esc(p.category)}</span><span class="badge">${esc(productMeta(p))}</span><div>$${Number(p.retail||0).toFixed(2)}</div>${last?`<small class="${fresh(last)?'fresh':'stale'}">${esc(store(last.storeId)?.name||'')} · ${fmt(last.seenAt)}</small>`:'<small class="muted">No sightings</small>'}</div><div class="report-actions" onclick="event.stopPropagation()"><button class="btn" onclick="window.toggleFav('${p.id}')">${p.favorite?'★ Watching':'☆ Watch'}</button><div class="menu-wrap"><button class="btn kebab" onclick="window.toggleMenu(event,'product-${p.id}')">⋮</button><div class="context-menu" id="menu-product-${p.id}" hidden><button class="btn danger" onclick="window.requestDelete('product','${p.id}')">Delete product</button></div></div></div>`;return layout==='grid'?`<div class="card clickable cat-${p.category}" onclick="window.openProduct('${p.id}')">${body}</div>`:`<div class="item clickable cat-${p.category}" onclick="window.openProduct('${p.id}')">${body}</div>`}
function renderProducts(){let layout=localStorage.getItem('crt_productLayout')||'list';$('products').innerHTML=`<div class="toolbar"><input id="productSearch" placeholder="Search products, sets, brands, or Beyblade models"><select id="categoryFilter"><option value="">All categories</option><option>TCG</option><option>Squishies</option><option>Beyblade</option></select><div class="segmented"><button id="listViewBtn">List</button><button id="gridViewBtn">Grid</button></div></div><div id="productList"></div>`;const draw=()=>{const q=$('productSearch').value.toLowerCase(),c=$('categoryFilter').value;const rows=db.products.filter(p=>(!c||p.category===c)&&JSON.stringify(p).toLowerCase().includes(q));$('listViewBtn').classList.toggle('active',layout==='list');$('gridViewBtn').classList.toggle('active',layout==='grid');$('productList').innerHTML=`<div class="${layout==='grid'?'grid':'list'}">${rows.map(p=>productCard(p,layout)).join('')}</div>`};$('productSearch').oninput=$('categoryFilter').onchange=draw;$('listViewBtn').onclick=()=>{layout='list';localStorage.setItem('crt_productLayout',layout);draw()};$('gridViewBtn').onclick=()=>{layout='grid';localStorage.setItem('crt_productLayout',layout);draw()};draw()}
function renderStores(){$('stores').innerHTML=`<div class="toolbar"><input id="storeSearch" placeholder="Search store or address"><select id="retailerFilter"><option value="">Both retailers</option><option>Walmart</option><option>Target</option></select></div><div id="storeList"></div>`;const draw=()=>{const q=$('storeSearch').value.toLowerCase(),ret=$('retailerFilter').value;const rows=db.stores.filter(s=>(!ret||s.retailer===ret)&&JSON.stringify(s).toLowerCase().includes(q));$('storeList').innerHTML=`<div class="list">${rows.map(s=>{const reports=db.sightings.filter(r=>r.storeId===s.id),freshCount=reports.filter(fresh).length;return `<div class="item ${reports.length?'clickable':''}" ${reports.length?`onclick="window.openStore('${s.id}')"`:''}><div class="store-icon ${s.retailer.toLowerCase()}"><img src="${logo(s)}" alt="${esc(s.retailer)}"></div><div><h3>${esc(s.name)}</h3><div>${esc(s.address)}</div><small class="muted">Approx. ${s.distance} mi · ${esc(s.phone||'')}</small><div class="store-summary"><span class="badge">${reports.length} report${reports.length===1?'':'s'}</span><span class="badge fresh">${freshCount} fresh</span></div></div><div class="actions" onclick="event.stopPropagation()"><button class="btn" onclick="window.openSchedule('${s.id}')">Restock days</button><a class="btn" target="_blank" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.address)}">Directions</a></div></div>`}).join('')}</div>`};$('storeSearch').oninput=$('retailerFilter').onchange=draw;draw()}
function renderCalendar(){const selected=new Set();$('calendar').innerHTML=`<p class="muted">Observed patterns are planning hints, not inventory guarantees.</p><div class="multi-store-filter">${db.stores.map(s=>`<label><input type="checkbox" value="${s.id}"> ${esc(s.name)}</label>`).join('')}</div><div class="toolbar"><button class="btn" id="clearStoreFilters">Show all stores</button></div><div id="calendarBody"></div>`;const draw=()=>{const rows=db.schedules.filter(s=>!selected.size||selected.has(s.storeId));const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];$('calendarBody').innerHTML=`<div class="calendar">${days.map(d=>`<div class="day"><strong>${d}</strong>${rows.filter(s=>s.days.includes(d)).map(s=>`<div class="event" onclick="window.openSchedule('${s.storeId}','${s.id}')"><b>${esc(store(s.storeId)?.name||s.retailer)}</b><br>${esc(s.title)} · ${esc(s.time||'')}</div>`).join('')}</div>`).join('')}</div><h2>Schedule details</h2><div class="list">${rows.map(scheduleCard).join('')||'<div class="empty">No schedules match.</div>'}</div>`};document.querySelectorAll('.multi-store-filter input').forEach(i=>i.onchange=()=>{i.checked?selected.add(i.value):selected.delete(i.value);draw()});$('clearStoreFilters').onclick=()=>{selected.clear();document.querySelectorAll('.multi-store-filter input').forEach(i=>i.checked=false);draw()};draw()}
function scheduleCard(s){return `<div class="card clickable" onclick="window.openSchedule('${s.storeId}','${s.id}')"><strong>${esc(store(s.storeId)?.name||s.retailer)}</strong><h3>${esc(s.title)}</h3><div>${esc(s.days.join(', '))} · ${esc(s.time||'')}</div><span class="badge">${esc(s.category)}</span><span class="badge">${esc(s.type)}</span><p class="muted">${esc(s.notes||'')}</p><small class="muted">${s.updates?.length||0} logged update${s.updates?.length===1?'':'s'}</small></div>`}
let mapObj;function drawMap(){if(!window.L)return;if(mapObj)mapObj.remove();mapObj=L.map('map').setView([30.31,-95.49],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(mapObj);db.stores.forEach(s=>{const cls=s.retailer.toLowerCase();const icon=L.divIcon({className:'',html:`<div class="map-pin ${cls}"><span></span></div>`,iconSize:[30,30],iconAnchor:[15,30]});const n=db.sightings.filter(r=>r.storeId===s.id&&fresh(r)).length;L.marker([s.lat,s.lng],{icon}).addTo(mapObj).bindPopup(`<b>${esc(s.name)}</b><br>${esc(s.address)}<br>${n} fresh reports`)})}
function renderWatchlist(){$('watchlist').innerHTML=`<h2>Watched product reports</h2>${reportList(db.sightings.filter(r=>product(r.productId)?.favorite))}<h2>Watched products</h2><div class="list">${db.products.filter(p=>p.favorite).map(p=>productCard(p,'list')).join('')||'<div class="empty">Nothing watched yet.</div>'}</div>`}
function renderHistory(){$('history').innerHTML=`<p class="muted">Reports remain here after the two-hour freshness window.</p>${reportList(db.sightings.slice())}`}
function renderSettings(){$('settings').innerHTML=`<div class="split"><div class="card"><h2>Export data</h2><p class="muted">Download products, stores, sightings, schedules, and audit logs.</p><button class="btn primary" id="exportBtn">Export JSON</button></div><div class="card"><h2>Import data</h2><input type="file" id="importFile" accept="application/json"><button class="btn" id="importBtn">Import</button></div><div class="card"><h2>Reset prototype</h2><p class="muted">Clears browser changes and reloads the seed JSON.</p><button class="btn danger" id="resetBtn">Reset local data</button></div><div class="card"><h2>Prototype permissions</h2><p class="muted">Anyone can update statuses and schedules. Delete controls are hidden inside three-dot menus and require the administrator passcode.</p></div></div>`;$('exportBtn').onclick=exportData;$('importBtn').onclick=importData;$('resetBtn').onclick=()=>{if(confirm('Reset all local prototype data?')){FILES.forEach(f=>localStorage.removeItem('crt_'+f));location.reload()}}}
function fillSelects(){if(!$('sightingForm'))return;$('sightingForm').productId.innerHTML=db.products.map(p=>`<option value="${p.id}">${esc(productTitle(p))}</option>`).join('');$('sightingForm').storeId.innerHTML=db.stores.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}
async function fileData(file){return new Promise((res,rej)=>{const r=new FileReader;r.onload=()=>res(r.result);r.onerror=rej;r.readAsDataURL(file)})}
async function addProduct(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));const category=f.category;const p={id:'p'+Date.now(),category,game:category==='TCG'?f.game:'',setName:category==='TCG'?f.setName:'',brand:category==='Squishies'?f.brand:'',productName:category==='Beyblade'?f.beyModel:f.productName,beyModel:category==='Beyblade'?f.beyModel:'',beyType:category==='Beyblade'?f.beyType:'',name:category==='Beyblade'?`Beyblade: ${f.beyModel}`:f.productName,retail:+f.retail||0,image:f.image,imageSource:f.imageSource,walmart:category==='Beyblade'?f.walmart:'',target:category==='Beyblade'?f.target:'',identifiers:f.identifiers,notes:f.notes,favorite:false,active:true};db.products.push(p);save('products');e.target.reset();updateProductFields();$('productDialog').close();renderAll()}
async function addSighting(e){e.preventDefault();const fd=new FormData(e.target),f=Object.fromEntries(fd);const t=new Date(f.seenAt);if(t>Date.now()+300000)return alert('Sighting time cannot be in the future.');let photo=f.photo;if(fd.get('photoFile')?.size)photo=await fileData(fd.get('photoFile'));db.sightings.push({...f,id:'r'+Date.now(),seenAt:t.toISOString(),quantity:f.quantity===''?'':+f.quantity,quantityKnown:f.quantity!=='',photo,updates:[]});save('sightings');e.target.reset();$('sightingDialog').close();renderAll()}
window.toggleFav=id=>{const p=product(id);p.favorite=!p.favorite;save('products');renderAll()};
window.toggleMenu=(e,id)=>{e.stopPropagation();const menu=$('menu-'+id),will=menu.hidden;document.querySelectorAll('.context-menu').forEach(m=>m.hidden=true);menu.hidden=!will};
window.openStatusUpdate=id=>{const r=db.sightings.find(x=>x.id===id);$('statusForm').reportId.value=id;$('statusForm').status.value=r.status;$('statusForm').quantity.value=r.quantityKnown?r.quantity:'';$('statusForm').updatedBy.value=r.reporter||'Deanna';$('statusForm').updatedSeenAt.value=nowLocal();$('statusForm').note.value='';$('statusForm').photo.value='';$('statusDialog').showModal()};
async function saveStatusUpdate(e){e.preventDefault();const fd=new FormData(e.target),f=Object.fromEntries(fd),r=db.sightings.find(x=>x.id===f.reportId);if(!r)return;const t=new Date(f.updatedSeenAt);if(t>Date.now()+300000)return alert('Update time cannot be in the future.');let newPhoto=f.photo;if(fd.get('photoFile')?.size)newPhoto=await fileData(fd.get('photoFile'));const log={from:r.status,to:f.status,previousQuantity:r.quantityKnown?r.quantity:'Unknown',quantity:f.quantity===''?'Unknown':+f.quantity,previousSeenAt:r.seenAt,updatedAt:t.toISOString(),updatedBy:f.updatedBy,note:f.note,photo:newPhoto||''};r.status=f.status;r.quantity=f.quantity===''?'':+f.quantity;r.quantityKnown=f.quantity!=='';r.seenAt=t.toISOString();r.reporter=f.updatedBy;if(newPhoto)r.photo=newPhoto;r.updates.push(log);save('sightings');$('statusDialog').close();renderAll();window.openReport(r.id)}
window.requestDelete=(type,id)=>{const code=prompt('Enter administrator passcode:');if(code===null)return;if(code!=='12345')return alert('Incorrect passcode. Nothing was deleted.');if(!confirm('Permanently delete this entry?'))return;if(type==='sighting')db.sightings=db.sightings.filter(x=>x.id!==id);if(type==='product'){if(db.sightings.some(x=>x.productId===id))return alert('Delete its sightings first.');db.products=db.products.filter(x=>x.id!==id)}save(type==='sighting'?'sightings':'products');$('detailDialog').close();renderAll()};
window.copyReport=id=>{const r=db.sightings.find(x=>x.id===id),p=product(r.productId),s=store(r.storeId);const text=`**Restock Found — ${s.name}**\n${productTitle(p)}\nStatus: ${r.status.replaceAll('-',' ')}\nQuantity: ${r.quantityKnown?r.quantity:'Unknown'}\nSeen: ${fmt(r.seenAt)}\nLocation: ${r.inStoreLocation||'Not provided'}\nReported by ${r.reporter||'Unknown'}`;navigator.clipboard.writeText(text);alert('Discord report copied!')};
window.openProduct=id=>{const p=product(id),reports=db.sightings.filter(r=>r.productId===id);$('detailContent').innerHTML=`<div class="detail-head"><h2>${esc(productTitle(p))}</h2><button class="btn" onclick="detailDialog.close()">Close</button></div><div class="detail-product"><div class="thumb large">${p.image?`<img src="${esc(p.image)}" alt="">`:esc(p.category[0])}</div><div><span class="badge">${esc(p.category)}</span><span class="badge">${esc(productMeta(p))}</span><p>Retail: $${Number(p.retail||0).toFixed(2)}</p><p>${esc(p.notes||'')}</p>${p.category==='Beyblade'?`${p.walmart?`<a class="btn" target="_blank" href="${esc(p.walmart)}">Walmart product</a>`:''}${p.target?`<a class="btn" target="_blank" href="${esc(p.target)}">Target product</a>`:''}`:''}</div></div><h2>Sightings</h2>${reportList(reports)}`;$('detailDialog').showModal()};
window.openReport=id=>{const r=db.sightings.find(x=>x.id===id),p=product(r.productId),s=store(r.storeId);const timeline=[{to:r.status,updatedAt:r.seenAt,updatedBy:r.reporter,note:r.notes,photo:r.photo,quantity:r.quantityKnown?r.quantity:'Unknown',initial:true},...(r.updates||[])].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt));$('detailContent').innerHTML=`<div class="detail-head"><div><h2>${esc(productTitle(p))}</h2><div>${esc(s.name)} · ${esc(s.address)}</div></div><button class="btn" onclick="detailDialog.close()">Close</button></div><p><span class="status-${r.status}"><b>${esc(r.status.replaceAll('-',' '))}</b></span> · ${r.quantityKnown?`Qty ${r.quantity}`:'Quantity unknown'} · <span class="${fresh(r)?'fresh':'stale'}">${fresh(r)?'Fresh':'Stale'}</span></p><p><b>In-store location:</b> ${esc(r.inStoreLocation||'Not provided')}</p>${r.photo?`<img class="sighting-photo" src="${esc(r.photo)}" alt="Sighting photo">`:''}<div class="actions"><button class="btn primary" onclick="window.openStatusUpdate('${r.id}')">Update status</button><button class="btn" onclick="window.copyReport('${r.id}')">Copy Discord report</button><div class="menu-wrap"><button class="btn kebab" onclick="window.toggleMenu(event,'detail-${r.id}')">⋮</button><div class="context-menu" id="menu-detail-${r.id}" hidden><button class="btn danger" onclick="window.requestDelete('sighting','${r.id}')">Delete entry</button></div></div></div><h2>Update timeline</h2>${timeline.map(x=>`<div class="timeline-entry"><strong>${x.initial?'Initial report':`${esc(x.from?.replaceAll('-',' ')||'unknown')} → ${esc(x.to.replaceAll('-',' '))}`}</strong><div>${fmt(x.updatedAt)} · ${esc(x.updatedBy||'Unknown')} · Qty ${esc(x.quantity)}</div>${x.note?`<p>${esc(x.note)}</p>`:''}${x.photo?`<img src="${esc(x.photo)}" alt="Update photo">`:''}</div>`).join('')}`;$('detailDialog').showModal()};
window.openStore=id=>{const s=store(id),reports=db.sightings.filter(r=>r.storeId===id);$('detailContent').innerHTML=`<div class="detail-head"><div><h2>${esc(s.name)}</h2><div>${esc(s.address)}</div></div><button class="btn" onclick="detailDialog.close()">Close</button></div><div class="actions"><button class="btn" onclick="window.openSchedule('${s.id}')">Restock days</button><a class="btn" target="_blank" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.address)}">Directions</a></div><h2>Reports</h2>${reportList(reports)}`;$('detailDialog').showModal()};
window.openSchedule=(storeId,scheduleId='')=>{const existing=scheduleId?db.schedules.find(x=>x.id===scheduleId):db.schedules.find(x=>x.storeId===storeId);const s=store(storeId);$('scheduleForm').reset();$('scheduleDialogTitle').textContent=`Restock days · ${s.name}`;$('scheduleForm').storeId.value=storeId;$('scheduleForm').scheduleId.value=existing?.id||'';$('scheduleForm').title.value=existing?.title||`${s.name} Restock Days`;$('scheduleForm').category.value=existing?.category||'All';$('scheduleForm').time.value=existing?.time||'';$('scheduleForm').type.value=existing?.type||'Observed pattern';$('scheduleForm').notes.value=existing?.notes||'';$('scheduleForm').updatedBy.value='Deanna';document.querySelectorAll('#scheduleForm input[name="days"]').forEach(i=>i.checked=existing?.days?.includes(i.value)||false);const logs=existing?.updates||[];let logBox=$('scheduleForm').querySelector('.schedule-history');if(logBox)logBox.remove();$('scheduleForm').insertAdjacentHTML('beforeend',logs.length?`<div class="schedule-history"><h3>Schedule update log</h3>${[...logs].reverse().map(l=>`<div class="timeline-entry"><strong>${esc(l.updatedBy)}</strong> · ${fmt(l.updatedAt)}<div>${esc(l.previousDays.join(', ')||'None')} → ${esc(l.newDays.join(', ')||'None')}</div>${l.note?`<p>${esc(l.note)}</p>`:''}</div>`).join('')}</div>`:'');$('scheduleDialog').showModal()};
function saveSchedule(e){e.preventDefault();const fd=new FormData(e.target),f=Object.fromEntries(fd),days=fd.getAll('days');let s=f.scheduleId?db.schedules.find(x=>x.id===f.scheduleId):null;if(s){s.updates=s.updates||[];s.updates.push({previousDays:[...s.days],newDays:[...days],previousTime:s.time,newTime:f.time,previousNotes:s.notes,newNotes:f.notes,updatedBy:f.updatedBy,updatedAt:new Date().toISOString(),note:f.updateNote});Object.assign(s,{title:f.title,category:f.category,time:f.time,type:f.type,notes:f.notes,days})}else{s={id:'s'+Date.now(),storeId:f.storeId,retailer:store(f.storeId)?.retailer||'',title:f.title,category:f.category,time:f.time,type:f.type,notes:f.notes,days,updates:[{previousDays:[],newDays:[...days],updatedBy:f.updatedBy,updatedAt:new Date().toISOString(),note:f.updateNote}]};db.schedules.push(s)}save('schedules');$('scheduleDialog').close();renderAll()}
function exportData(){const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='conroe-restock-backup.json';a.click()}
function importData(){const file=$('importFile').files[0];if(!file)return alert('Choose a JSON backup first.');const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);FILES.forEach(f=>{if(Array.isArray(x[f])){db[f]=x[f];save(f)}});normalize();renderAll();alert('Imported.')}catch{alert('That file is not a valid backup.')}};r.readAsText(file)}
boot();
