const FILES=['stores','products','sightings','schedules']; const db={};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
async function boot(){for(const f of FILES){const saved=localStorage.getItem('crt_'+f);db[f]=saved?JSON.parse(saved):await fetch(`data/${f}.json`).then(r=>r.json())}bind();renderAll();setInterval(renderAll,60000)}
const save=f=>localStorage.setItem('crt_'+f,JSON.stringify(db[f])); const product=id=>db.products.find(x=>x.id===id); const store=id=>db.stores.find(x=>x.id===id);
function age(r){return Date.now()-new Date(r.seenAt).getTime()} function fresh(r){return age(r)>=0&&age(r)<7200000} function fmt(t){return new Date(t).toLocaleString([], {dateStyle:'short',timeStyle:'short'})}
function bind(){document.querySelectorAll('#nav button').forEach(b=>b.onclick=()=>{show(b.dataset.view,b.textContent);closeMobileMenu()});document.querySelectorAll('.close').forEach(b=>b.onclick=()=>b.closest('dialog').close());mobileMenuBtn.onclick=toggleMobileMenu;navBackdrop.onclick=closeMobileMenu;addProductBtn.onclick=()=>productDialog.showModal();addSightingBtn.onclick=()=>{fillSelects();sightingForm.seenAt.value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);sightingDialog.showModal()};productForm.onsubmit=addProduct;sightingForm.onsubmit=addSighting;statusForm.onsubmit=saveStatusUpdate;document.addEventListener('click',e=>{if(!e.target.closest('.menu-wrap'))document.querySelectorAll('.context-menu').forEach(m=>m.hidden=true)})}
function toggleMobileMenu(){let open=document.querySelector('.sidebar').classList.toggle('open');navBackdrop.classList.toggle('show',open);mobileMenuBtn.setAttribute('aria-expanded',open);mobileMenuBtn.textContent=open?'✕':'☰'}
function closeMobileMenu(){document.querySelector('.sidebar').classList.remove('open');navBackdrop.classList.remove('show');mobileMenuBtn.setAttribute('aria-expanded','false');mobileMenuBtn.textContent='☰'}
function show(id,title){document.querySelectorAll('.view').forEach(v=>v.classList.toggle('active',v.id===id));document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===id));pageTitle.textContent=title;if(id==='mapview')setTimeout(drawMap,80)}
function renderAll(){renderDashboard();renderProducts();renderStores();renderCalendar();renderWatchlist();renderHistory();renderSettings()}
function renderDashboard(){const fr=db.sightings.filter(fresh);const stale=db.sightings.filter(r=>!fresh(r));dashboard.innerHTML=`<div class="grid"><div class="card metric"><span class="muted">Fresh reports</span><strong>${fr.length}</strong><span>under 2 hours old</span></div><div class="card metric"><span class="muted">Watchlist</span><strong>${db.products.filter(p=>p.favorite).length}</strong><span>favorite products</span></div><div class="card metric"><span class="muted">Stores</span><strong>${db.stores.length}</strong><span>Walmart + Target</span></div><div class="card metric"><span class="muted">Needs recheck</span><strong>${stale.length}</strong><span>stale reports</span></div></div><h2>Fresh restocks</h2>${reportList(fr)}<h2>Upcoming patterns</h2>${scheduleList(db.schedules.slice(0,4))}`}
function reportList(rows){if(!rows.length)return '<div class="card empty">No matching reports yet.</div>';return `<div class="list">${[...rows].sort((a,b)=>new Date(b.seenAt)-new Date(a.seenAt)).map(r=>{let p=product(r.productId),s=store(r.storeId),logs=r.updates||[];return `<div class="item cat-${esc(p?.category)}"><div class="thumb">${p?.image?`<img src="${esc(p.image)}">`:esc((p?.subcategory||'?')[0])}</div><div><strong>${esc(p?.name)}</strong><div>${esc(s?.name)} · <span class="status-${r.status}">${esc(r.status.replaceAll('-',' '))}</span>${r.quantityKnown||r.quantity!==''?` · Qty ${esc(r.quantity)}`:''}</div><small class="${fresh(r)?'fresh':'stale'}">${fresh(r)?'Fresh':'Stale'} · ${fmt(r.seenAt)}</small><div class="muted">${esc(r.inStoreLocation||r.notes||'')}</div>${logs.length?`<details class="update-log"><summary>${logs.length} status update${logs.length===1?'':'s'}</summary>${[...logs].reverse().map(l=>`<div class="log-entry"><strong>${esc(l.from?.replaceAll('-',' ')||'unknown')} → ${esc(l.to.replaceAll('-',' '))}</strong>${fmt(l.updatedAt)} · ${esc(l.updatedBy||'Unknown')}${l.note?`<br>${esc(l.note)}`:''}</div>`).join('')}</details>`:''}</div><div class="report-actions"><button class="btn primary" onclick="window.openStatusUpdate('${r.id}')">Update status</button><button class="btn" onclick="window.copyReport('${r.id}')">Discord</button><div class="menu-wrap"><button class="btn kebab" aria-label="More options" onclick="window.toggleReportMenu(event,'${r.id}')">⋮</button><div class="context-menu" id="menu-${r.id}" hidden><button class="btn danger" onclick="window.requestDeleteReport('${r.id}')">Delete entry</button></div></div></div></div>`}).join('')}</div>`}
function filters(){return `<div class="toolbar"><input id="productSearch" placeholder="Search products"><select id="categoryFilter"><option value="">All categories</option><option>TCG</option><option>Squishies</option><option>Beyblade</option></select></div>`}
function renderProducts(){products.innerHTML=filters()+`<div id="productList"></div>`;const draw=()=>{let q=productSearch.value.toLowerCase(),c=categoryFilter.value;let rows=db.products.filter(p=>(!c||p.category===c)&&JSON.stringify(p).toLowerCase().includes(q));productList.innerHTML=`<div class="grid">${rows.map(p=>`<div class="card cat-${p.category}"><div class="thumb">${p.image?`<img src="${esc(p.image)}">`:esc(p.subcategory[0])}</div><h3>${esc(p.name)}</h3><span class="badge">${esc(p.category)} · ${esc(p.subcategory)}</span><p>$${Number(p.retail||0).toFixed(2)}</p><p class="muted">${esc(p.notes)}</p><div class="actions">${p.walmart?`<a class="btn" target="_blank" href="${esc(p.walmart)}">Walmart</a>`:''}${p.target?`<a class="btn" target="_blank" href="${esc(p.target)}">Target</a>`:''}<button class="btn" onclick="window.toggleFav('${p.id}')">${p.favorite?'★ Watching':'☆ Watch'}</button></div></div>`).join('')}</div>`};productSearch.oninput=categoryFilter.onchange=draw;draw()}
function renderStores(){stores.innerHTML=`<div class="toolbar"><input id="storeSearch" placeholder="Search store or address"><select id="retailerFilter"><option value="">Both retailers</option><option>Walmart</option><option>Target</option></select></div><div id="storeList"></div>`;const draw=()=>{let q=storeSearch.value.toLowerCase(),r=retailerFilter.value;let rows=db.stores.filter(s=>(!r||s.retailer===r)&&JSON.stringify(s).toLowerCase().includes(q));storeList.innerHTML=`<div class="list">${rows.map(s=>`<div class="item"><div class="thumb">${s.retailer[0]}</div><div><strong>${esc(s.name)}</strong><div>${esc(s.address)}</div><small class="muted">Approx. ${s.distance} mi · ${esc(s.phone)}</small><div>${db.sightings.filter(x=>x.storeId===s.id&&fresh(x)).length} fresh reports</div></div><div class="actions"><a class="btn" target="_blank" href="${esc(s.url)}">Store page</a><a class="btn" target="_blank" href="https://www.google.com/maps/search/?api=1&query=${encodeURIComponent(s.address)}">Directions</a></div></div>`).join('')}</div>`};storeSearch.oninput=retailerFilter.onchange=draw;draw()}
function scheduleList(rows){return `<div class="list">${rows.map(s=>`<div class="card"><strong>${esc(s.title)}</strong><div>${esc(s.days.join(', '))} · ${esc(s.time)}</div><span class="badge">${esc(s.type)}</span><p class="muted">${esc(s.notes)}</p></div>`).join('')}</div>`}
function renderCalendar(){const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];calendar.innerHTML=`<p class="muted">Observed patterns are planning hints, not inventory guarantees.</p><div class="calendar">${days.map(d=>`<div class="day"><strong>${d}</strong>${db.schedules.filter(s=>s.days.includes(d)).map(s=>`<div class="event">${esc(s.title)}<br>${esc(s.time)}</div>`).join('')}</div>`).join('')}</div><h2>Schedule details</h2>${scheduleList(db.schedules)}`}
let mapObj;function drawMap(){if(!window.L)return;if(mapObj)mapObj.remove();mapObj=L.map('map').setView([30.31,-95.49],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(mapObj);db.stores.forEach(s=>{let n=db.sightings.filter(r=>r.storeId===s.id&&fresh(r)).length;L.marker([s.lat,s.lng]).addTo(mapObj).bindPopup(`<b>${esc(s.name)}</b><br>${esc(s.address)}<br>${n} fresh reports`)})}
function renderWatchlist(){watchlist.innerHTML=reportList(db.sightings.filter(r=>product(r.productId)?.favorite))+`<h2>Watched products</h2><div class="grid">${db.products.filter(p=>p.favorite).map(p=>`<div class="card"><strong>${esc(p.name)}</strong><div class="muted">${esc(p.subcategory)}</div></div>`).join('')}</div>`}
function renderHistory(){history.innerHTML=`<p class="muted">Reports stay in history after the two-hour freshness window.</p>${reportList(db.sightings)}`}
function renderSettings(){settings.innerHTML=`<div class="split"><div class="card"><h2>Export data</h2><p class="muted">Download everything as one JSON backup.</p><button class="btn primary" id="exportBtn">Export JSON</button></div><div class="card"><h2>Import data</h2><input type="file" id="importFile" accept="application/json"><button class="btn" id="importBtn">Import</button></div><div class="card"><h2>Reset prototype</h2><p class="muted">Clears browser changes and reloads seed JSON files.</p><button class="btn danger" id="resetBtn">Reset local data</button></div></div>`;exportBtn.onclick=exportData;importBtn.onclick=importData;resetBtn.onclick=()=>{if(confirm('Reset all local prototype data?')){FILES.forEach(f=>localStorage.removeItem('crt_'+f));location.reload()}}}
function fillSelects(){sightingForm.productId.innerHTML=db.products.map(p=>`<option value="${p.id}">${esc(p.name)}</option>`).join('');sightingForm.storeId.innerHTML=db.stores.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('')}
async function fileData(file){return new Promise(res=>{let r=new FileReader;r.onload=()=>res(r.result);r.readAsDataURL(file)})}
async function addProduct(e){e.preventDefault();let f=new FormData(e.target),img=f.get('image');if(f.get('imageFile')?.size)img=await fileData(f.get('imageFile'));db.products.push({id:'p'+Date.now(),name:f.get('name'),retail:+f.get('retail'),category:f.get('category'),subcategory:f.get('subcategory'),image:img,walmart:f.get('walmart'),target:f.get('target'),identifiers:f.get('identifiers'),notes:f.get('notes'),favorite:false,active:true});save('products');e.target.reset();productDialog.close();renderAll()}
function addSighting(e){e.preventDefault();let f=Object.fromEntries(new FormData(e.target));let t=new Date(f.seenAt);if(t>Date.now()+300000)return alert('Sighting time cannot be in the future.');db.sightings.push({...f,id:'r'+Date.now(),quantity:f.quantity===''?'':+f.quantity,quantityKnown:f.quantity!=='',updates:[]});save('sightings');sightingDialog.close();renderAll()}
window.toggleFav=id=>{let p=product(id);p.favorite=!p.favorite;save('products');renderAll()};window.toggleReportMenu=(e,id)=>{e.stopPropagation();let menu=document.getElementById('menu-'+id),willOpen=menu.hidden;document.querySelectorAll('.context-menu').forEach(m=>m.hidden=true);menu.hidden=!willOpen};window.openStatusUpdate=id=>{let r=db.sightings.find(x=>x.id===id);statusForm.reportId.value=id;statusForm.status.value=r.status;statusForm.quantity.value=r.quantityKnown?r.quantity:'';statusForm.updatedBy.value=r.reporter||'Deanna';statusForm.updatedSeenAt.value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);statusForm.note.value='';statusDialog.showModal()};function saveStatusUpdate(e){e.preventDefault();let f=Object.fromEntries(new FormData(e.target)),r=db.sightings.find(x=>x.id===f.reportId);if(!r)return;let updateTime=new Date(f.updatedSeenAt);if(updateTime>Date.now()+300000)return alert('Update time cannot be in the future.');let from=r.status,previousSeenAt=r.seenAt;r.status=f.status;r.quantity=f.quantity===''?'':+f.quantity;r.quantityKnown=f.quantity!=='';r.seenAt=updateTime.toISOString();r.reporter=f.updatedBy;r.updates=r.updates||[];r.updates.push({from,to:f.status,quantity:r.quantity,updatedBy:f.updatedBy,note:f.note,previousSeenAt,updatedAt:updateTime.toISOString()});save('sightings');statusDialog.close();renderAll()}window.requestDeleteReport=id=>{let code=prompt('Enter administrator passcode to delete this entry:');if(code===null)return;if(code!=='12345')return alert('Incorrect passcode. Entry was not deleted.');if(confirm('Permanently delete this entry?')){db.sightings=db.sightings.filter(r=>r.id!==id);save('sightings');renderAll()}};window.copyReport=id=>{let r=db.sightings.find(x=>x.id===id),p=product(r.productId),s=store(r.storeId);let text=`**Restock Found — ${s.name}**\n${p.name}\nStatus: ${r.status.replaceAll('-',' ')}\nQuantity: ${r.quantityKnown?r.quantity:'Unknown'}\nSeen: ${fmt(r.seenAt)}\nLocation: ${r.inStoreLocation||'Not provided'}\nReported by ${r.reporter||'Unknown'}`;navigator.clipboard.writeText(text);alert('Discord report copied!')};
function exportData(){let a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='conroe-restock-backup.json';a.click()}
function importData(){let file=importFile.files[0];if(!file)return alert('Choose a JSON backup first.');let r=new FileReader;r.onload=()=>{try{let x=JSON.parse(r.result);FILES.forEach(f=>{if(Array.isArray(x[f])){db[f]=x[f];save(f)}});renderAll();alert('Imported.')}catch{alert('That file is not a valid backup.')}};r.readAsText(file)}boot();
