const FILES=['products','stores','sightings','schedules'];
const db={};
const $=id=>document.getElementById(id);
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
const fmt=d=>new Date(d).toLocaleString([], {dateStyle:'medium',timeStyle:'short'});
const nowLocal=()=>{const d=new Date();d.setMinutes(d.getMinutes()-d.getTimezoneOffset());return d.toISOString().slice(0,16)};
const slug=s=>String(s||'').toLowerCase().replace(/[^a-z0-9]+/g,' ').trim();
const product=id=>db.products.find(x=>x.id===id)||{};
const store=id=>db.stores.find(x=>x.id===id)||{};
const logo=s=>`assets/icons/${String(s?.retailer||'').toLowerCase()}.png`;
const productTitle=p=>p.category==='TCG'?`${p.game} · ${p.setName} · ${p.productName}`:p.category==='Squishies'?`${p.brand} · ${p.productName}`:`Beyblade · ${p.beyModel||p.productName}`;
const productMeta=p=>p.category==='TCG'?`${p.game} · ${p.setName}`:p.category==='Squishies'?p.brand:p.beyType;
const seenTime=r=>r.seenAt||new Date(Date.now()+(r.relativeHours||0)*3600000).toISOString();
const fresh=r=>Date.now()-new Date(seenTime(r)).getTime()<=2*3600000;
const latestForProduct=id=>db.sightings.filter(r=>r.productId===id).sort((a,b)=>new Date(seenTime(b))-new Date(seenTime(a)))[0];
const save=k=>localStorage.setItem(`crt-v3-${k}`,JSON.stringify(db[k]));
const unique=a=>[...new Set(a.filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b)));
let activeView='dashboard', productLayout=localStorage.getItem('crt-layout')||'list', map, productFilters={}, historyFilter='all', storeFilter='all', selectedScheduleStores=[];

async function boot(){
 for(const f of FILES){
  const saved=localStorage.getItem(`crt-v3-${f}`);
  if(saved){db[f]=JSON.parse(saved)}else{db[f]=await fetch(`data/${f}.json`).then(r=>r.json())}
 }
 normalize(); bind(); fillSelects(); renderAll();
}
function normalize(){
 db.products.forEach(p=>{p.favorite=!!p.favorite;p.active=p.active!==false});
 db.sightings.forEach(r=>{if(!r.seenAt&&r.relativeHours!==undefined)r.seenAt=new Date(Date.now()+r.relativeHours*3600000).toISOString();r.updates=r.updates||[];r.quantityKnown=r.quantityKnown??(r.quantity!==''&&r.quantity!=null)});
 db.schedules.forEach(s=>{s.days=s.days||[];s.updates=s.updates||[]});
 if(!selectedScheduleStores.length)selectedScheduleStores=db.stores.map(s=>s.id);
}
function bind(){
 $('nav').addEventListener('click',e=>{const b=e.target.closest('[data-view]');if(b)showView(b.dataset.view)});
 $('mobileMenuBtn').onclick=()=>document.body.classList.toggle('nav-open');$('navBackdrop').onclick=()=>document.body.classList.remove('nav-open');
 $('addMenuBtn').onclick=e=>{e.stopPropagation();$('addMenu').hidden=!$('addMenu').hidden;$('addMenuBtn').setAttribute('aria-expanded',String(!$('addMenu').hidden))};
 document.addEventListener('click',e=>{if(!e.target.closest('.add-menu-wrap'))$('addMenu').hidden=true});
 $('addProductBtn').onclick=()=>{$('addMenu').hidden=true;updateProductForm();$('productDialog').showModal()};
 $('addSightingBtn').onclick=()=>{$('addMenu').hidden=true;fillSelects();$('sightingForm').seenAt.value=nowLocal();updateSourceFields();$('sightingDialog').showModal()};
 $('addScheduleBtn').onclick=()=>{$('addMenu').hidden=true;openScheduleEditor()};
 document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());
 $('productCategory').onchange=updateProductForm;$('sightingSource').onchange=updateSourceFields;$('scheduleStore').onchange=()=>loadScheduleForm($('scheduleStore').value);
 $('productForm').onsubmit=saveProduct;$('sightingForm').onsubmit=saveSighting;$('statusForm').onsubmit=saveStatus;$('scheduleForm').onsubmit=saveSchedule;
}
function showView(v){activeView=v;document.querySelectorAll('.view').forEach(x=>x.classList.toggle('active',x.id===v));document.querySelectorAll('#nav button').forEach(x=>x.classList.toggle('active',x.dataset.view===v));$('pageTitle').textContent=v==='calendar'?'Restock Days':({mapview:'Map',settings:'Data'}[v]||v[0].toUpperCase()+v.slice(1));document.body.classList.remove('nav-open');renderAll();if(v==='mapview')setTimeout(renderMap,50)}
function renderAll(){renderDashboard();renderProducts();renderStores();renderCalendar();renderWatchlist();renderHistory();renderSettings();if(activeView==='mapview')setTimeout(renderMap,20)}
function fillSelects(){
 const po=db.products.map(p=>`<option value="${p.id}">${esc(productTitle(p))}</option>`).join('');
 const st=db.stores.map(s=>`<option value="${s.id}">${esc(s.name)}</option>`).join('');
 $('sightingForm').productId.innerHTML=po;$('sightingForm').storeId.innerHTML=st;$('scheduleStore').innerHTML=`<option value="">Choose a store</option>${st}`;
}
function updateProductForm(){const c=$('productCategory').value;$('tcgGameWrap').hidden=c!=='TCG';$('setWrap').hidden=c!=='TCG';$('brandWrap').hidden=c!=='Squishies';$('beyModelWrap').hidden=c!=='Beyblade';$('beyTypeWrap').hidden=c!=='Beyblade';$('productNameWrap').hidden=c==='Beyblade';$('beyLinks').hidden=c!=='Beyblade';$('productNameLabel').textContent=c==='TCG'?'Item type':'Item name'}
function updateSourceFields(){const online=$('sightingSource').value==='Online retailer';document.querySelectorAll('.online-only').forEach(x=>x.hidden=!online);const link=$('sightingForm').productLink;link.required=online;if(!online){link.value='';$('sightingForm').pickup.value='unknown';$('sightingForm').shipping.value='unknown'}}
function card(label,value,action,desc=''){return `<button class="stat-card" onclick="${action}" aria-label="${esc(label)}: ${value}"><span>${esc(label)}</span><strong>${value}</strong>${desc?`<small>${esc(desc)}</small>`:''}</button>`}
function renderDashboard(){const freshReports=db.sightings.filter(fresh),stale=db.sightings.filter(r=>!fresh(r)),storesWith=new Set(db.sightings.map(r=>r.storeId));$('dashboard').innerHTML=`<div class="stats">${card('Fresh reports',freshReports.length,"window.goHistory('fresh')")}${card('Watched products',db.products.filter(p=>p.favorite).length,"window.goWatchlist()")}${card('Stores with reports',storesWith.size,"window.goStoresWithReports()")}${card('Stale reports',stale.length,"window.goHistory('stale')")}</div><h2>Recent sightings</h2>${reportList([...db.sightings].sort((a,b)=>new Date(seenTime(b))-new Date(seenTime(a))).slice(0,10))}`}
window.goHistory=f=>{historyFilter=f;showView('history')};window.goWatchlist=()=>showView('watchlist');window.goStoresWithReports=()=>{storeFilter='with-reports';showView('stores')};
function filterOption(label,name,values,current,multiple=false){return `<label>${esc(label)}<select data-filter="${name}" ${multiple?'multiple':''}><option value="">All</option>${values.map(v=>`<option ${current===v?'selected':''}>${esc(v)}</option>`).join('')}</select></label>`}
function renderProducts(){
 const productsWith=db.products.filter(p=>db.sightings.some(r=>r.productId===p.id)); const noSight=db.products.filter(p=>!db.sightings.some(r=>r.productId===p.id));
 let visible=[...productsWith];
 if(productFilters.category)visible=visible.filter(p=>p.category===productFilters.category);
 if(productFilters.product)visible=visible.filter(p=>(p.game||p.brand||p.beyModel)===productFilters.product);
 if(productFilters.set)visible=visible.filter(p=>p.setName===productFilters.set);
 if(productFilters.itemType)visible=visible.filter(p=>(p.productName||p.beyType)===productFilters.itemType || p.beyType===productFilters.itemType);
 if(productFilters.retailer)visible=visible.filter(p=>db.sightings.some(r=>r.productId===p.id&&store(r.storeId).retailer===productFilters.retailer));
 if(productFilters.store)visible=visible.filter(p=>db.sightings.some(r=>r.productId===p.id&&r.storeId===productFilters.store));
 if(productFilters.status)visible=visible.filter(p=>db.sightings.some(r=>r.productId===p.id&&r.status===productFilters.status));
 if(productFilters.freshness)visible=visible.filter(p=>db.sightings.some(r=>r.productId===p.id&&(productFilters.freshness==='Fresh'?fresh(r):!fresh(r))));
 if(productFilters.watched)visible=visible.filter(p=>p.favorite);
 const order=productFilters.sort||'newest';visible.sort((a,b)=>{const aa=new Date(seenTime(latestForProduct(a.id))),bb=new Date(seenTime(latestForProduct(b.id)));return order==='oldest'?aa-bb:bb-aa});
 const categories=unique(productsWith.map(p=>p.category));let scoped=productFilters.category?productsWith.filter(p=>p.category===productFilters.category):productsWith;
 const products=unique(scoped.map(p=>p.game||p.brand||p.beyModel));if(productFilters.product)scoped=scoped.filter(p=>(p.game||p.brand||p.beyModel)===productFilters.product);
 const sets=unique(scoped.map(p=>p.setName));const itemTypes=unique(scoped.map(p=>p.category==='Beyblade'?p.beyType:p.productName));
 const chips=Object.entries(productFilters).filter(([,v])=>v&&v!==false).map(([k,v])=>`<button class="filter-chip" onclick="window.clearProductFilter('${k}')">${esc(k)}: ${esc(v===true?'Yes':v)} ×</button>`).join('');
 $('products').innerHTML=`<div class="product-toolbar"><input id="productSearch" placeholder="Search products, sets, brands, or Beyblade models"><button class="btn" id="filterToggle">☰ Filter${Object.keys(productFilters).length?` (${Object.keys(productFilters).length})`:''}</button><div class="segmented"><button class="${productLayout==='list'?'active':''}" data-layout="list">List</button><button class="${productLayout==='grid'?'active':''}" data-layout="grid">Grid</button></div></div><div id="filterPanel" class="filter-panel" hidden>${filterOption('Category','category',categories,productFilters.category)}${filterOption('Product / game / brand','product',products,productFilters.product)}${productFilters.category==='TCG'?filterOption('Set','set',sets,productFilters.set):''}${filterOption('Item type','itemType',itemTypes,productFilters.itemType)}${filterOption('Retailer','retailer',['Target','Walmart'],productFilters.retailer)}${filterOption('Store','store',db.stores.map(s=>s.name),store(productFilters.store).name)}${filterOption('Stock status','status',['in-stock','low-stock','out-of-stock','unknown'],productFilters.status)}${filterOption('Freshness','freshness',['Fresh','Stale'],productFilters.freshness)}<label>Watched only<select data-filter="watched"><option value="">All</option><option value="true" ${productFilters.watched?'selected':''}>Watched</option></select></label>${filterOption('Sort','sort',['newest','oldest'],productFilters.sort||'newest')}<button class="btn" id="clearFilters">Clear all</button></div>${chips?`<div class="filter-chips">${chips}</div>`:''}<div id="productResults" class="products-${productLayout}">${visible.length?visible.map(productCard).join(''):'<div class="empty">No products match these filters.</div>'}</div><details class="no-sightings"><summary>Products with no sightings <span>${noSight.length}</span></summary><div class="no-sighting-list">${noSight.map(noSightingCard).join('')}</div></details>`;
 $('filterToggle').onclick=()=>{$('filterPanel').hidden=!$('filterPanel').hidden};$('clearFilters').onclick=()=>{productFilters={};renderProducts()};
 document.querySelectorAll('#filterPanel [data-filter]').forEach(el=>el.onchange=()=>{let v=el.value;if(el.dataset.filter==='store')v=db.stores.find(s=>s.name===v)?.id||'';if(el.dataset.filter==='watched')v=v==='true';productFilters[el.dataset.filter]=v||'';if(el.dataset.filter==='category'){delete productFilters.product;delete productFilters.set;delete productFilters.itemType}if(el.dataset.filter==='product'){delete productFilters.set;delete productFilters.itemType}renderProducts()});
 document.querySelectorAll('[data-layout]').forEach(b=>b.onclick=()=>{productLayout=b.dataset.layout;localStorage.setItem('crt-layout',productLayout);renderProducts()});
 $('productSearch').oninput=e=>{const q=slug(e.target.value);document.querySelectorAll('#productResults .product-card').forEach(c=>c.hidden=!slug(c.dataset.search).includes(q))};
}
window.clearProductFilter=k=>{delete productFilters[k];renderProducts()};
function productCard(p){const r=latestForProduct(p.id);return `<article class="product-card" data-search="${esc(productTitle(p)+' '+productMeta(p))}" onclick="window.openProduct('${p.id}')"><div class="thumb">${p.image?`<img src="${esc(p.image)}" alt="">`:esc(p.category[0])}</div><div class="product-body"><h3>${esc(productTitle(p))}</h3><div><span class="badge">${esc(p.category)}</span><span class="badge">${esc(productMeta(p))}</span></div><div>$${Number(p.retail||0).toFixed(2)}</div><div class="${fresh(r)?'fresh':'stale'}">${r?`${fresh(r)?'Fresh':'Stale'} · ${esc(store(r.storeId).name)} · ${fmt(seenTime(r))}`:'No sightings'}</div></div><button class="btn" onclick="event.stopPropagation();window.toggleWatch('${p.id}')">${p.favorite?'★ Watching':'☆ Watch'}</button></article>`}
function noSightingCard(p){return `<article class="compact-card"><div><strong>${esc(productTitle(p))}</strong><div class="muted">${esc(p.category)} · ${esc(productMeta(p))} · $${Number(p.retail||0).toFixed(2)}</div></div><div class="actions"><button class="btn" onclick="window.toggleWatch('${p.id}')">${p.favorite?'★ Watching':'☆ Watch'}</button><button class="btn primary" onclick="window.addSightingFor('${p.id}')">Add sighting</button></div></article>`}
window.addSightingFor=id=>{fillSelects();$('sightingForm').productId.value=id;$('sightingForm').seenAt.value=nowLocal();updateSourceFields();$('sightingDialog').showModal()};
window.toggleWatch=id=>{const p=product(id);p.favorite=!p.favorite;save('products');renderAll()};
function renderStores(){let stores=[...db.stores];if(storeFilter==='with-reports')stores=stores.filter(s=>db.sightings.some(r=>r.storeId===s.id));$('stores').innerHTML=`${storeFilter==='with-reports'?'<div class="filter-chips"><button class="filter-chip" onclick="window.clearStoreFilter()">Has reports ×</button></div>':''}<div class="store-grid">${stores.map(s=>{const reports=db.sightings.filter(r=>r.storeId===s.id),sched=db.schedules.filter(x=>x.storeId===s.id);return `<article class="store-card" onclick="window.openStore('${s.id}')"><div class="store-icon ${s.retailer.toLowerCase()}"><img src="${logo(s)}" alt="${esc(s.retailer)}"></div><div><h3>${esc(s.name)}</h3><p>${esc(s.address)}</p><p>${reports.length} reports · ${sched.length?sched.map(x=>`${x.days.join('/')}${x.time?` ${x.time}`:''}`).join(' • '):'No restock days'}</p></div></article>`}).join('')}</div>`}
window.clearStoreFilter=()=>{storeFilter='all';renderStores()};
function renderCalendar(){const selected=new Set(selectedScheduleStores),schedules=db.schedules.filter(s=>selected.has(s.storeId));const days=['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'];$('calendar').innerHTML=`<p class="muted">Observed patterns are planning hints, not inventory guarantees.</p><div class="schedule-tools"><div class="multi-select" id="storeMulti"><button class="btn multi-trigger" id="storeMultiBtn">${selected.size===db.stores.length?'All stores':`${selected.size} stores selected`} ▾</button><div class="multi-panel" id="storeMultiPanel" hidden><input id="storeMultiSearch" placeholder="Search stores"><div class="multi-actions"><button class="btn" id="selectAllStores">Select all</button><button class="btn" id="clearAllStores">Clear all</button></div><div id="storeChoices">${db.stores.map(s=>`<label><input type="checkbox" value="${s.id}" ${selected.has(s.id)?'checked':''}>${esc(s.name)}</label>`).join('')}</div></div></div><button class="btn primary" onclick="window.openScheduleEditor()">+ Add schedule</button></div><div class="week-grid">${days.map(d=>`<section><strong>${d}</strong>${schedules.filter(s=>s.days.includes(d)).map(s=>`<button class="event ${store(s.storeId).retailer.toLowerCase()}" onclick="window.viewSchedule('${s.storeId}','${s.id}')"><b>${esc(store(s.storeId).name)}</b><span>${esc(s.title)}</span><small>${esc(s.time||'')}</small></button>`).join('')}</section>`).join('')}</div><h2>Schedule details</h2><div>${schedules.length?schedules.map(scheduleCard).join(''):'<div class="empty">Select a store with a reported schedule.</div>'}</div>`;
 $('storeMultiBtn').onclick=e=>{e.stopPropagation();$('storeMultiPanel').hidden=!$('storeMultiPanel').hidden};$('selectAllStores').onclick=()=>{selectedScheduleStores=db.stores.map(s=>s.id);renderCalendar()};$('clearAllStores').onclick=()=>{selectedScheduleStores=[];renderCalendar()};
 document.querySelectorAll('#storeChoices input').forEach(i=>i.onchange=()=>{selectedScheduleStores=i.checked?unique([...selectedScheduleStores,i.value]):selectedScheduleStores.filter(x=>x!==i.value);renderCalendar()});$('storeMultiSearch').oninput=e=>{const q=slug(e.target.value);document.querySelectorAll('#storeChoices label').forEach(l=>l.hidden=!slug(l.textContent).includes(q))};
}
function scheduleCard(s){const st=store(s.storeId);return `<article class="schedule-card ${st.retailer.toLowerCase()}" onclick="window.viewSchedule('${s.storeId}','${s.id}')"><div class="store-icon ${st.retailer.toLowerCase()}"><img src="${logo(st)}" alt="${esc(st.retailer)}"></div><div><strong>${esc(st.name)}</strong><h3>${esc(s.title)}</h3><p>${esc(s.days.join(', '))}${s.time?` · ${esc(s.time)}`:''}</p><span class="badge">${esc(s.category)}</span><span class="badge">${esc(s.type)}</span><p>${esc(s.notes||'')}</p><small>${s.updates.length} logged updates</small></div></article>`}
function reportList(reports){if(!reports.length)return '<div class="empty">No reports.</div>';return `<div class="report-list">${reports.map(r=>{const p=product(r.productId),s=store(r.storeId);return `<article class="report-card" onclick="window.openReport('${r.id}')"><div><h3>${esc(productTitle(p))}</h3><p>${esc(s.name)} · ${fmt(seenTime(r))}</p><span class="status-${r.status}">${esc(r.status.replaceAll('-',' '))}</span> <span class="${fresh(r)?'fresh':'stale'}">${fresh(r)?'Fresh':'Stale'}</span></div><div>${r.quantityKnown?`Qty ${r.quantity}`:'Qty unknown'}</div></article>`}).join('')}</div>`}
function renderWatchlist(){const ps=db.products.filter(p=>p.favorite);$('watchlist').innerHTML=ps.length?`<div class="products-list">${ps.map(productCard).join('')}</div>`:'<div class="empty">No watched products yet.</div>'}
function renderHistory(){let rs=[...db.sightings];if(historyFilter==='fresh')rs=rs.filter(fresh);if(historyFilter==='stale')rs=rs.filter(r=>!fresh(r));rs.sort((a,b)=>new Date(seenTime(b))-new Date(seenTime(a)));$('history').innerHTML=`<div class="actions"><button class="btn ${historyFilter==='all'?'primary':''}" onclick="window.setHistoryFilter('all')">All</button><button class="btn ${historyFilter==='fresh'?'primary':''}" onclick="window.setHistoryFilter('fresh')">Fresh</button><button class="btn ${historyFilter==='stale'?'primary':''}" onclick="window.setHistoryFilter('stale')">Stale</button></div>${reportList(rs)}`}
window.setHistoryFilter=f=>{historyFilter=f;renderHistory()};
function renderSettings(){$('settings').innerHTML=`<div class="settings-card"><h2>Prototype data</h2><p>This version stores changes in this browser using localStorage.</p><div class="actions"><button class="btn" onclick="window.exportData()">Export JSON</button><label class="btn">Choose backup<input id="importFile" type="file" accept="application/json" hidden></label><button class="btn" onclick="window.importData()">Import JSON</button><button class="btn danger" onclick="window.resetDemo()">Reset demo data</button></div></div>`}
function renderMap(){if(!window.L)return;if(!map){map=L.map('map').setView([30.25,-95.49],10);L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'© OpenStreetMap'}).addTo(map)}map.eachLayer(l=>{if(l instanceof L.Marker)map.removeLayer(l)});db.stores.forEach(s=>{const count=db.sightings.filter(r=>r.storeId===s.id).length;const icon=L.divIcon({className:'',html:`<div class="map-pin ${s.retailer.toLowerCase()}"><img src="${logo(s)}"></div>`,iconSize:[38,38]});L.marker([s.lat,s.lng],{icon}).addTo(map).bindPopup(`<b>${esc(s.name)}</b><br>${count} reports`)})}
function saveProduct(e){e.preventDefault();const f=Object.fromEntries(new FormData(e.target));let display=f.category==='Beyblade'?f.beyModel:f.productName;if(!display.trim())return alert('Enter an item name.');if(f.category==='Beyblade'){const key=slug(f.beyModel).replace(/\s/g,'');const matches=db.products.filter(p=>p.category==='Beyblade'&&slug(p.beyModel).replace(/\s/g,'')===key);if(matches.length)return alert(`That appears to match ${productTitle(matches[0])}. Use the existing item instead.`);const close=db.products.filter(p=>p.category==='Beyblade'&&(slug(p.beyModel).includes(slug(f.beyModel))||slug(f.beyModel).includes(slug(p.beyModel))));if(close.length&&!confirm(`Similar item found: ${productTitle(close[0])}. Create another anyway?`))return}
 db.products.push({id:'p'+Date.now(),...f,retail:Number(f.retail||0),productName:display,name:display,favorite:false,active:true});save('products');e.target.reset();$('productDialog').close();fillSelects();renderAll()}
async function saveSighting(e){e.preventDefault();const fd=new FormData(e.target),f=Object.fromEntries(fd);if(f.source==='Online retailer'&&!f.productLink)return alert('An exact product link is required for online retailer sightings.');let photo='';const file=fd.get('photoFile');if(file&&file.size)photo=await fileToData(file);db.sightings.push({id:'r'+Date.now(),...f,quantity:Number(f.quantity||0),quantityKnown:f.quantity!=='',seenAt:new Date(f.seenAt).toISOString(),photo,updates:[]});save('sightings');e.target.reset();$('sightingDialog').close();fillSelects();renderAll()}
const fileToData=file=>new Promise(resolve=>{const r=new FileReader();r.onload=()=>resolve(r.result);r.readAsDataURL(file)});
window.openStatusUpdate=id=>{const r=db.sightings.find(x=>x.id===id);$('statusForm').reportId.value=id;$('statusForm').status.value=r.status;$('statusForm').quantity.value=r.quantityKnown?r.quantity:'';$('statusForm').updatedSeenAt.value=nowLocal();$('statusDialog').showModal()};
async function saveStatus(e){e.preventDefault();const fd=new FormData(e.target),f=Object.fromEntries(fd),r=db.sightings.find(x=>x.id===f.reportId);const file=fd.get('photoFile'),newPhoto=file&&file.size?await fileToData(file):f.photo;const t=new Date(f.updatedSeenAt);r.updates.push({from:r.status,to:f.status,previousQuantity:r.quantityKnown?r.quantity:'Unknown',quantity:f.quantity!==''?Number(f.quantity):'Unknown',updatedAt:t.toISOString(),updatedBy:f.updatedBy,note:f.note,photo:newPhoto});r.status=f.status;r.quantity=Number(f.quantity||0);r.quantityKnown=f.quantity!=='';r.seenAt=t.toISOString();r.reporter=f.updatedBy;if(newPhoto)r.photo=newPhoto;save('sightings');$('statusDialog').close();renderAll();window.openReport(r.id)}
window.toggleMenu=(e,id)=>{e.stopPropagation();const m=$(`menu-${id}`);m.hidden=!m.hidden};
window.requestDelete=(type,id)=>{const code=prompt('Enter administrator passcode:');if(code===null)return;if(code!=='12345')return alert('Incorrect passcode.');if(!confirm('Permanently delete this entry?'))return;if(type==='sighting')db.sightings=db.sightings.filter(x=>x.id!==id);if(type==='product'){if(db.sightings.some(x=>x.productId===id))return alert('Delete its sightings first.');db.products=db.products.filter(x=>x.id!==id)}save(type==='sighting'?'sightings':'products');$('detailDialog').close();renderAll()};
window.openProduct=id=>{const p=product(id),reports=db.sightings.filter(r=>r.productId===id).sort((a,b)=>new Date(seenTime(b))-new Date(seenTime(a)));$('detailContent').innerHTML=`<div class="detail-head"><h2>${esc(productTitle(p))}</h2><button class="btn" onclick="detailDialog.close()">Close</button></div><div class="detail-product"><div class="thumb large">${esc(p.category[0])}</div><div><span class="badge">${esc(p.category)}</span><span class="badge">${esc(productMeta(p))}</span><p>Retail: $${Number(p.retail||0).toFixed(2)}</p><p>${esc(p.notes||'')}</p></div></div><h2>Sightings</h2>${reportList(reports)}`;$('detailDialog').showModal()};
window.openReport=id=>{const r=db.sightings.find(x=>x.id===id),p=product(r.productId),s=store(r.storeId);const timeline=[{to:r.status,updatedAt:seenTime(r),updatedBy:r.reporter,note:r.notes,photo:r.photo,quantity:r.quantityKnown?r.quantity:'Unknown',initial:true},...(r.updates||[])].sort((a,b)=>new Date(b.updatedAt)-new Date(a.updatedAt));$('detailContent').innerHTML=`<div class="detail-head"><div><h2>${esc(productTitle(p))}</h2><div>${esc(s.name)} · ${esc(s.address)}</div></div><button class="btn" onclick="detailDialog.close()">Close</button></div><p><span class="status-${r.status}"><b>${esc(r.status.replaceAll('-',' '))}</b></span> · ${r.quantityKnown?`Qty ${r.quantity}`:'Quantity unknown'} · <span class="${fresh(r)?'fresh':'stale'}">${fresh(r)?'Fresh':'Stale'}</span></p><p><b>In-store location:</b> ${esc(r.inStoreLocation||'Not provided')}</p>${r.source==='Online retailer'?`<p><b>Pickup:</b> ${esc(r.pickup||'unknown')} · <b>Shipping:</b> ${esc(r.shipping||'unknown')}</p><p><a class="btn" target="_blank" href="${esc(r.productLink)}">Open product page</a></p>`:''}${r.photo?`<img class="sighting-photo" src="${esc(r.photo)}" alt="Sighting photo">`:''}<div class="actions"><button class="btn primary" onclick="window.openStatusUpdate('${r.id}')">Update status</button><div class="menu-wrap"><button class="btn" onclick="window.toggleMenu(event,'detail-${r.id}')">⋮</button><div class="context-menu" id="menu-detail-${r.id}" hidden><button class="btn danger" onclick="window.requestDelete('sighting','${r.id}')">Delete entry</button></div></div></div><h2>Update timeline</h2>${timeline.map(x=>`<div class="timeline-entry"><strong>${x.initial?'Initial report':`${esc(x.from||'unknown')} → ${esc(x.to)}`}</strong><div>${fmt(x.updatedAt)} · ${esc(x.updatedBy||'Unknown')} · Qty ${esc(x.quantity)}</div>${x.note?`<p>${esc(x.note)}</p>`:''}</div>`).join('')}`;$('detailDialog').showModal()};
window.openStore=id=>{const s=store(id),reports=db.sightings.filter(r=>r.storeId===id),schedules=db.schedules.filter(x=>x.storeId===id);$('detailContent').innerHTML=`<div class="detail-head"><div class="store-detail-title"><div class="store-icon ${s.retailer.toLowerCase()}"><img src="${logo(s)}" alt="${esc(s.retailer)}"></div><div><h2>${esc(s.name)}</h2><div>${esc(s.address)}</div></div></div><button class="btn" onclick="detailDialog.close()">Close</button></div><h2>Restock days</h2>${schedules.length?schedules.map(scheduleCard).join(''):'<div class="empty">No restock schedule reported.</div>'}<div class="modal-actions"><button class="btn primary" onclick="window.openScheduleEditor('${s.id}')">${schedules.length?'Add another schedule':'Add restock days'}</button></div><h2>Reports</h2>${reportList(reports)}`;$('detailDialog').showModal()};
window.viewSchedule=(storeId,scheduleId='')=>{const st=store(storeId),existing=scheduleId?db.schedules.find(x=>x.id===scheduleId):db.schedules.find(x=>x.storeId===storeId);$('detailContent').innerHTML=`<div class="detail-head"><div><h2>Restock days · ${esc(st.name)}</h2><div>${esc(st.address)}</div></div><button class="btn" onclick="detailDialog.close()">Close</button></div>${existing?`<div class="schedule-view ${st.retailer.toLowerCase()}"><h3>${esc(existing.title)}</h3><p><b>Days:</b> ${esc(existing.days.join(', '))}</p><p><b>Time:</b> ${esc(existing.time||'Not specified')}</p><p><b>Category:</b> ${esc(existing.category)}</p><p><b>Pattern:</b> ${esc(existing.type)}</p><p>${esc(existing.notes||'')}</p></div><h3>Update log</h3>${existing.updates.length?[...existing.updates].reverse().map(scheduleLogEntry).join(''):'<p class="muted">No updates logged yet.</p>'}`:'<div class="empty">No restock schedule has been added.</div>'}<div class="modal-actions"><button class="btn primary" onclick="window.openScheduleEditor('${storeId}','${existing?.id||''}')">${existing?'Edit schedule':'Add schedule'}</button></div>`;$('detailDialog').showModal()};
function scheduleLogEntry(l){return `<div class="timeline-entry"><strong>${esc(l.updatedBy||'Unknown')}</strong> · ${fmt(l.updatedAt)}<div>${esc((l.previousDays||[]).join(', ')||'None')} → ${esc((l.newDays||[]).join(', ')||'None')}</div>${l.note?`<p>${esc(l.note)}</p>`:''}</div>`}
window.openScheduleEditor=(storeId='',scheduleId='')=>openScheduleEditor(storeId,scheduleId);
function openScheduleEditor(storeId='',scheduleId=''){$('detailDialog').close();$('scheduleForm').reset();fillSelects();$('scheduleStore').value=storeId;loadScheduleForm(storeId,scheduleId);$('scheduleDialog').showModal()}
function loadScheduleForm(storeId,scheduleId=''){const st=store(storeId);const existing=scheduleId?db.schedules.find(x=>x.id===scheduleId):db.schedules.find(x=>x.storeId===storeId);$('scheduleForm').scheduleId.value=existing?.id||'';$('scheduleDialogTitle').textContent=st?`Add or update restock days · ${st.name}`:'Add or update restock days';$('scheduleForm').title.value=existing?.title||(st?`${st.name} Restock Days`:'');$('scheduleForm').category.value=existing?.category||'All';$('scheduleForm').time.value=existing?.time||'';$('scheduleForm').type.value=existing?.type||'Observed pattern';$('scheduleForm').notes.value=existing?.notes||'';$('scheduleForm').updateNote.value='';document.querySelectorAll('#scheduleForm input[name="days"]').forEach(i=>i.checked=existing?.days?.includes(i.value)||false)}
function saveSchedule(e){e.preventDefault();const fd=new FormData(e.target),f=Object.fromEntries(fd),days=fd.getAll('days');if(!f.storeId)return alert('Choose a store.');let s=f.scheduleId?db.schedules.find(x=>x.id===f.scheduleId):null;if(s){s.updates.push({previousDays:[...s.days],newDays:[...days],previousTime:s.time,newTime:f.time,updatedBy:f.updatedBy,updatedAt:new Date().toISOString(),note:f.updateNote});Object.assign(s,{storeId:f.storeId,retailer:store(f.storeId).retailer,title:f.title,category:f.category,time:f.time,type:f.type,notes:f.notes,days})}else{s={id:'s'+Date.now(),storeId:f.storeId,retailer:store(f.storeId).retailer,title:f.title,category:f.category,time:f.time,type:f.type,notes:f.notes,days,updates:[{previousDays:[],newDays:[...days],updatedBy:f.updatedBy,updatedAt:new Date().toISOString(),note:f.updateNote}]};db.schedules.push(s)}save('schedules');$('scheduleDialog').close();renderAll();window.viewSchedule(f.storeId,s.id)}
window.exportData=()=>{const a=document.createElement('a');a.href=URL.createObjectURL(new Blob([JSON.stringify(db,null,2)],{type:'application/json'}));a.download='conroe-restock-backup.json';a.click()};
window.importData=()=>{const file=$('importFile').files[0];if(!file)return alert('Choose a JSON backup first.');const r=new FileReader();r.onload=()=>{try{const x=JSON.parse(r.result);FILES.forEach(f=>{if(Array.isArray(x[f])){db[f]=x[f];save(f)}});normalize();renderAll();alert('Imported.')}catch{alert('That file is not valid.')}};r.readAsText(file)};
window.resetDemo=()=>{if(confirm('Clear local changes and reload the packaged demo data?')){FILES.forEach(f=>localStorage.removeItem(`crt-v3-${f}`));location.reload()}};
boot();
